### ISSUE TITLE
Use test.check / core.typed

### ISSUE THREAD

**Issue by atroche** [weavejester/compojure#121]
Hi @weavejester,

If I wrote up a test suite using test.check, would you consider merging it in? Or do you feel it wouldn't be appropriate / would clutter the repo?

How about annotating the library with core.typed?

Cheers!

**Comment by dijonkitchen** [comment]
Is this still relevant or should it be closed?

**Comment by weavejester** [comment]
This can probably be closed. If needs be a PR can be re-opened if anyone really wants to add more tests.
