### ISSUE TITLE
context macro failing for a context of "/"

### ISSUE THREAD

**Issue by csdrane** [weavejester/compojure#125]
The `POST` macro does not appear to work within the `context` macro. E.g.

```
(context "/" {{foo :bar} :params}
  (POST "/baz" [] (do-something)
```

This is caused by 

```
(defn- method-matches? [method request]
  (let [request-method (request :request-method)
        form-method    (or (get-in request [:form-params "_method"])
                           (get-in request [:multipart-params "_method"]))]
    (if (and form-method (= request-method :post))
      (.equalsIgnoreCase (name method) form-method)
      (= method request-method))))
```

Destructuring strips off the params, so the route will not be executed.

**Comment by 3duard0** [comment]
The problem seems to be that the context path cannot end with a '/'. This doesn't seem to work either:
````clojure
(context "/user/" {{foo :bar} :params}
  (POST "/baz" [] (do-something)))
````

**Comment by weavejester** [comment]
Well, that would match "/user//baz".

**Comment by 3duard0** [comment]
@csdrane example also seems to work with "//baz", if that's the acceptable behavior I don't think there's a bug. However if it should match "/baz" instead, then it should also match "/user/baz".

**Comment by mrkam2** [comment]
> Incidentally, this also appears to work:
> 
> ```clojure
> (context "" {{foo :bar} :params}
>   (POST "/baz" [] (do-something)))
> ```

`context ""` was causing the following error when trying to access `/` route which has no handler in the context:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
  Stack trace: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at clojure.core$subs.invokeStatic(core.clj:4987)
	at compojure.core$remove_suffix.invokeStatic(core.clj:184)
	at compojure.core$if_context$fn__89206.invoke(core.clj:197)
	at compojure.core$routing$fn__89182.invoke(core.clj:127)
	at clojure.core$some.invokeStatic(core.clj:2701)
	at compojure.core$routing.invokeStatic(core.clj:124)
	at compojure.core$routing.doInvoke(core.clj:124)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at compojure.core$routes$fn__89186.invoke(core.clj:129)
```

**Comment by mrkam2** [comment]
I wasn't able to reproduce the issue outside of my project but `remove-suffix` is invoked with `"" "/"` arguments.

**Comment by mrkam2** [comment]
Found the issue: one of our middlewares was removing trailing slash from the URI and accidentally were converting `"/"` to an empty string `""`.
