### ISSUE TITLE
context macro performance

### ISSUE THREAD

**Issue by kul** [weavejester/compojure#133]
For the following namespace

```clojure
(ns context-hotspot.handler
  (:require [compojure.core :refer :all]
            [compojure.handler :as handler]
            [compojure.route :as route]
            [ring.middleware.defaults :refer [wrap-defaults site-defaults]]
            [ring.adapter.jetty :as j]))

(defroutes app-routes
  (GET "/ping" [] "pong")
  (context "/context" []
           (GET "/ping" [] "pong"))
  (route/not-found "Not Found"))

(def app
  (handler/api app-routes))

(defn -main
  []
  (def server (j/run-jetty app {:port 8080 :join? false})))
```

```bash
% ./wrk -t16 -c512 -d10s http://localhost:8080/context/ping 
Requests/sec:  13748.38

% ./wrk -t16 -c512 -d10s http://localhost:8080/ping
Requests/sec:  49561.31
```

This is a lot of perfromance hit for just a common context imo.

**Comment by weavejester** [comment]
Well, remember that the context is matching two routes, so you'd expect it to be at least twice as slow, since it's doing twice the work. It's also changing the `:context`, `:path-info` keys and the parameter map, which account for the remaining time.

However, perhaps there are some optimisations that could be done to improve the performance a little, and I'd be interested in any pull requests with benchmarks to that effect.

**Comment by ryfow** [comment]
I think the problem is that `clout/route-compile` is getting called for routes inside the context on each request. This repl session shows how much faster the context is when route-compile is memoized.

```clojure
user=> (require 'compojure.core-test)
nil

user=> (in-ns 'compojure.core-test)
#<Namespace compojure.core-test>

compojure.core-test=> (def c (context "/foo" [] (GET "/bar" [] "bar")))
#'compojure.core-test/c

compojure.core-test=> (c (mock/request :get "/foo/bar"))
{:status 200, :headers {"Content-Type" "text/html; charset=utf-8"}, :body "bar"}

compojure.core-test=> (time (dotimes [n 10000] (c (mock/request :get "/foo/bar"))))
"Elapsed time: 1683.139 msecs"
nil

compojure.core-test=> (in-ns 'clout.core)
#<Namespace clout.core>

clout.core=> (def route-compile (memoize route-compile))
#'clout.core/route-compile

clout.core=> (in-ns 'compojure.core-test)
#<Namespace compojure.core-test>

compojure.core-test=> (c (mock/request :get "/foo/bar"))
{:status 200, :headers {"Content-Type" "text/html; charset=utf-8"}, :body "bar"}

compojure.core-test=> (time (dotimes [n 10000] (c (mock/request :get "/foo/bar"))))
"Elapsed time: 142.369 msecs"
nil
```

**Comment by weavejester** [comment]
That's an extremely interesting result, @ryfow.

It looks like the private `prepare-route` function in `compojure.core` will result in routes being recompiled when placed within a closure. It should be relatively straightforward to force literal routes to be compiled at compile-time instead.

**Comment by weavejester** [comment]
I've fixed the issue with `route-compile` being called unnecessarily in 1.3.2-SNAPSHOT, and this results in a much closer benchmark:

```
~» wrk -t16 -c512 -d10s http://localhost:5000/ping
Requests/sec:  37605.05
~» wrk -t16 -c512 -d10s http://localhost:5000/context/ping
Requests/sec:  32287.16
```

@kul, it looks like I was wrong about the performance of `context` being close to optimum. I don't think we can get it much better than the above results, but I was wrong before, so perhaps it can be further improved beyond my expectations.

**Comment by ryfow** [comment]
Thanks for fixing this, @weavejester. I putzed around with it, but my macro-fu is weak.

Your fix knocked my routing time down by over 50% in one benchmark.

**Comment by kul** [comment]
@weavejester @ryfow thanks for putting time on this. I havent had time to look into it further. But the benchmark looks good enough that it wont affect any realistic scenario of using compojure imo. So i will be completely ok if you'd like to close this.
