### ISSUE TITLE
Instaparse Broken in Clojure-1.7.0-alpha6

### ISSUE THREAD

**Issue by bitnovus** [weavejester/compojure#137]
Hi James,

It looks like the latest Clojure (1.7.0-alpha6) changed the number of parameters for clojure.lang.LispReader$StringReader from two to four. Instaparse depended on StringReader and Compojure isn't building because of arity exceptions.

Any suggestions on how to move forward?

LispReader: https://github.com/clojure/clojure/commit/caa3b4fdc8da5880309b317d0045b1280181c452#diff-3a5dca122734225f3f60263876401aeb
InstaParse: https://github.com/Engelberg/instaparse/blob/d90d82351cbe106977150c9832f5b7d7797e0f20/src/instaparse/cfg.clj

Thanks for all of your hard work!

Best.
Daniel

**Comment by weavejester** [comment]
For reference, this is reported in Engelberg/instaparse#90. When that's fixed, I'll update Clout's dependencies.

**Comment by bitnovus** [comment]
It looks like Mark fixed it with version 1.3.6 of Instaparse.

**Comment by NoamB** [comment]
It also fails for me, and works with 1.3.6 Instaparse.

**Comment by bitnovus** [comment]
Thanks! Everything's building successfully now.

**Comment by NoamB** [comment]
Same here, thanks :)
