### ISSUE TITLE
Matching 'subpaths' alternative

### ISSUE THREAD

**Issue by dfrese** [weavejester/compojure#151]
A route like `(GET "/some/path/*" [*] ...)` causes a message to be printed out on stdout:

> WARNING: * should not be used as a route binding.

How can an arbitrary deep 'subpath' be matched otherwise, and could that be added to Wiki?
Alternatively, how can the warning be disabled?

**Comment by weavejester** [comment]
It's covered under the [Routes In Detail](https://github.com/weavejester/compojure/wiki/Routes-In-Detail) wiki page. You can specify a regular expression for a value, so:

    (GET "/some/path/:foo{.*}" [foo] ...)

Or:

    (GET ["/some/path/:foo", :foo #".*"] [foo] ...)

Either will work.

**Comment by dfrese** [comment]
Thank a lot! That works too.

(Mentioning that in the warning could be helpful to other people in the future).
