### ISSUE TITLE
Desctructuring problem with only rest args.

### ISSUE THREAD

**Issue by carrete** [weavejester/compojure#152]
When I don't specify any variables but do include rest args like `(ANY "/" [& args] error-405)` this is expanded into:

```clojure
(compojure.core/make-route
  nil
  {:source "/", :re #"/", :keys [], :absolute? false}
  (fn*
    ([request__2306__auto__]
      (let*
        [args (dissoc (:params request__2306__auto__))]
        (do error-405)))))
```

 `dissoc` is being called with just one parameter.

**Comment by weavejester** [comment]
What's the problem with that? `(dissoc m) => m`.

**Comment by carrete** [comment]
> What's the problem with that? (dissoc m) => m.

Sorry. Because eastwood complains. I assumed because of the complaint that this is incorrect.

**Comment by weavejester** [comment]
I don't think I'll change this. Eastwood probably shouldn't be checking macros, as those details are internal, and the JIT should make the difference between `(dissoc m)` and `m` moot.
