### ISSUE TITLE
Empty route with context?

### ISSUE THREAD

**Issue by ProjectFrank** [weavejester/compojure#153]
A route with an empty path (e.g. `(GET "" [] handler)` never gets matched.

The reason why I have an empty route is because I'm using `compojure.core/context` and I'd like to mount the empty route onto a context. Example:

```clojure
(context "/foo/bar" []
         (GET "" [] handler)
         (GET "/another-route" [] another-handler))
```

I could do this instead, but it's not as nice 😞 
```clojure
(routes
 (GET "/foo/bar" [] handler)
 (context "/foo/bar" []
          (GET "/another-route" [] another-handler)))
```

Would it be reasonable to support this?

**Comment by weavejester** [comment]
Try:

```clojure
(context "/foo/bar" []
  (GET "/" [] handler)
  (GET "/another-route" [] another-handler))
```

**Comment by ProjectFrank** [comment]
Would it be possible to do this without needing a trailing slash?

I've currently accomplished this by incorporating this middleware that replaces `compojure.core/if-route` if the given path is an empty string:

```
(defn if-empty-route
  [handler]
  (fn [{:keys [context uri] :as request}]
    (when (= context uri)
      (handler request))))
```

**Comment by weavejester** [comment]
You don't need a trailing slash. My previous example will match "/foo/bar".

If the context matches exactly, then the route inside the macro will be "/", rather than "". The reasoning behind this is that it allows functions to be written that are ignorant of whether they are in a context or not.

**Comment by ProjectFrank** [comment]
That makes a lot of sense 😃 

Thanks a lot and sorry for the noise!

**Comment by weavejester** [comment]
It's probably something that should be documented better. I'll make a note to add it to the wiki.
