### ISSUE TITLE
Reporting statistics to StatsD

### ISSUE THREAD

**Issue by erez-rabih** [weavejester/compojure#154]
Hi,
We're using compojure as our routing library and we would like to send statistics to a StatsD daemon which in turn feeds a Graphite backend with the statistics.

The way we'd like to do it is with a global middleware that will handle all routes and will send route specific data. For example, the following route definition:
(GET "/users/:uid" req (users/get req))
Should increment a counter for the metric named
`web.get.users.uid`

We don't want the specific uid to be present in the metric name, but the word uid itself. For that we need the general pattern the url was matched by. The reason we need it is because it is not a good practice to add Graphite metrics with specific data such as uids.

I had a look and saw that compojure adds a :compojure/route key to the request that is available only on the handler itself - (users/get uid)

I was wondering if that's possible to have pattern a route was matched by to a middleware and not to the end handler only.
Or, if there is another solution to report metrics by the pattern a route was matched by and not by the URI itself, I'd love to hear about that.

I hope the question is clear, if a clarification is needed I will be happy to supply it.

**Comment by weavejester** [comment]
You can use `compojure.core/wrap-routes` to inject a middleware function to be applied to routes after they've been matched.

So something like:

```clojure
(defn wrap-statsd [handler]
  (compojure/wrap-routes
   handler
   (fn [route-handler]
     (fn [request]
       (statsd/log-route (:compojure/route request))
       (route-handler request)))))
```

**Comment by erez-rabih** [comment]
@weavejester Thanks for the fast reply.

Your solution seems like a regular middleware which I have already tried with no success.
If I replace the `statsd/log-route` with `println` I always get nil.
It seems that the routes have not been matched yet in this stage.

**Comment by weavejester** [comment]
Are you using `wrap-routes`? That function injects middleware into the route, so that it's applied after the route is matched.

A quick REPL session confirms it works:

```clojure
user=> (use 'compojure.core)
nil
user=> (defn wrap-print-route [handler] (wrap-routes handler (fn [rhandler] (fn [req] (prn (:compojure/route req)) (rhandler req)))))
#'user/wrap-print-route
user=> (def rs (wrap-print-route (routes (GET "/foo" [] "foo") (GET "/bar" [] "bar"))))
#'user/rs
user=> (require '[ring.mock.request :as mock])
nil
user=> (rs (mock/request :get "/foo"))
[:get "/foo"]
{:status 200, :headers {"Content-Type" "text/html; charset=utf-8"}, :body "foo"}
user=> (rs (mock/request :get "/bar"))
[:get "/bar"]
{:status 200, :headers {"Content-Type" "text/html; charset=utf-8"}, :body "bar"}
```

**Comment by erez-rabih** [comment]
Strange indeed, even repeating your REPL session produced nil output for me:
```clojure
user=> (use 'compojure.core)
nil
user=> (defn wrap-print-route [handler] (wrap-routes handler (fn [rhandler] (fn [req] (prn (:compojure/route req)) (rhandler req)))))
#'user/wrap-print-route
user=> (def rs (wrap-print-route (routes (GET "/foo" [] "foo") (GET "/bar" [] "bar"))))
#'user/rs
user=> (require '[ring.mock.request :as mock])
nil
user=> (rs (mock/request :get "/foo"))
nil
{:body "foo", :headers {"Content-Type" "text/html; charset=utf-8"}, :status 200}
```

Maybe it is something related with versions?

**Comment by erez-rabih** [comment]
I confirm that upgrading from compojure 1.4.0 to 1.5.0 I get the same results you do in the REPL session.

Seems like it is a matter of versions.

Is there a changelog I can look at?

**Comment by erez-rabih** [comment]
We can close this issue now.

I am just curious what is the difference between 1.4.0 to 1.5.0 that makes this work correctly

**Comment by weavejester** [comment]
Take a look at [HISTORY.md](https://github.com/weavejester/compojure/blob/master/HISTORY.md). The `:compojure/route` key was only added in Compojure 1.5.0.
