### ISSUE TITLE
Renderable extends `APersistentMap` and not `IPersistentMap`

### ISSUE THREAD

**Issue by ztellman** [weavejester/compojure#159]
This means that things which are implementations of Clojure-compatible maps (such as https://github.com/ztellman/aleph/blob/master/src/aleph/http/core.clj#L207) will not be recognized as a valid response, as reported here: https://github.com/ztellman/aleph/issues/298.

I understand that by extending an interface over a protocol you risk intersecting implementations, but I'd argue the same is true for an abstract class.

**Comment by weavejester** [comment]
I dimly recall there being a reason for using `APersistentMap` over `IPersistentMap`, but I can't remember what it was. If there are no problems with using the interface over the abstract class, I agree we should switch to the interface.

**Comment by xiongtx** [comment]
> I dimly recall there being a reason for using `APersistentMap` over `IPersistentMap`

I can't imagine what it is--all `render` does is call `merge`.
