### ISSUE TITLE
images under folders with "ad" as the first two letters not loading.

### ISSUE THREAD

**Issue by dt1** [weavejester/compojure#162]
My file system is set up as "/resources/public/img"

When I create folders under /img/ with the names "ads" "ad-images" "adverts" or "adimg", the images in any of those folders do not load. This doesn't appear to affect all folder names beginning with "ad" because "address" is working fine.

It's also interesting because the the missing image square does not pop up on the site. The HTML inspector does say "could not load the file." I tested this with .png and .jpg.

I haven't tested this on all other folder trees.

I'm running Clojure 1.8.0, Compojure 1.5.1, on a Fedora 25 box. I'm deploying to Heroku and the same issue is occurring on the live site.

**Comment by weavejester** [comment]
Are you using an ad-blocker?

**Comment by dt1** [comment]
Yeah. Just tested on a browser w/o adblock and it works fine. Knew this was going to be dumb one, lol. 

Thank you.

**Comment by weavejester** [comment]
No problem :)
