### ISSUE TITLE
Upgrade TechEmpower Framework Benchmarks for compojure

### ISSUE THREAD

**Issue by mfirry** [weavejester/compojure#166]
I think those benchmarks might need an upgrade to the latest version of compojure.

Please have a [look](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Clojure/compojure/hello).

**Comment by weavejester** [comment]
Shouldn't this issue be on the TechEmpower repository?

**Comment by mfirry** [comment]
I guess it was a way for me to suggest compojure's contributors to keep an eye to that. That's all.

**Comment by mfirry** [comment]
@weavejester, I guess you can close this, right?

**Comment by weavejester** [comment]
Sure.
