### ISSUE TITLE
Destructuring Syntax typo

### ISSUE THREAD

**Issue by willspecht** [weavejester/compojure#168]
The post example reads:
`(POST "/foobar" [foo]
       (str "foo: " bar))`

but it should be: 
`(POST "/foobar" [foo]
       (str "foo: " foo))`

**Comment by weavejester** [comment]
Fixed. You can fix typos in the wiki yourself, rather than opening up an issue, if you like. A lot of the examples (like the one you spotted having a typo) were added that way to begin with.
