### ISSUE TITLE
How to defined nested routes with `wrap-json-body`

### ISSUE THREAD

**Issue by LukasRychtecky** [weavejester/compojure#173]
Hi, thank you for this library.

I run into an issue when having more routes wrapped into `wrap-json-body`.

```clojure
(context "/transactions" []
  (wrap-json-body
    (POST "/" [:as request]
      ...)))

(context "/transactions/:id" [id]
  (wrap-json-body
    (PUT "/" [:as request]
      ...)))
```

Second route's body will be `nil`, because of `InputStream` (as it's pointed here https://github.com/weavejester/compojure/wiki/Common-Problems#a-middleware-tries-to-read-the-body-of-a-request-but-finds-it-empty).

How can I define these routes?

Thanks for an answer.

**Comment by lvbarbosa** [comment]
Why don't you wrap them together inside the json middleware only once?

```clojure
(wrap-json-body
  (routes
     (context ...)
     (context ...))
```

**Comment by weavejester** [comment]
As @lvbarbosa mentions, you can apply the JSON middleware only once. It will only consume the body if the content type is JSON, so should be safe either way.

Otherwise, you can use the `compojure.core/wrap-routes` function.

**Comment by Atsman** [comment]
@LukasRychtecky if you get your answer, can we close issue?

**Comment by LukasRychtecky** [comment]
Yes, thank you for your help guys!
