### ISSUE TITLE
Can't user query parameters without a value

### ISSUE THREAD

**Issue by ElizabethForest** [weavejester/compojure#175]
Hi!

In the browser, you are able to do `mywebsite.com?param` and `param` shows up as a query param with an empty string, but when using compojure `param` doesn't show up in `:query-params`.

Doing `mywebsite.com?param=` gives the query-params of `{:param ""}` which is expected, but then if you do `mywebsite.com?param=1&param2` you get `{:param 1, :param2 nil}`.

It feels a little inconsistent, and I would like to be able to use `mywebsite.com?param`.

I am using `1.6.0`.

**Comment by weavejester** [comment]
Can you open this issue on [Ring](https://github.com/ring-clojure/ring)? Compojure doesn't have any opinion on how to parse query parameters.
