### ISSUE TITLE
Embed a Java servlet in a Ring/Compojure app

### ISSUE THREAD

**Issue by MichaelBlume** [weavejester/compojure#176]
Sometimes a dependency provides an out-of-the-box Servlet object. A good example is the `HystrixMetricsStreamServlet` which exposes metrics to an external hystrix dashboard. Is there a good one-size-fits-all way to embed such a Servlet in a Compojure/Ring app?

**Comment by weavejester** [comment]
There might be a library available to do that, but I'm not aware of one off hand. Compojure is just a routing library, so this is a little beyond its scope.

**Comment by jiacai2050** [comment]
@MichaelBlume I think this is what you need
- https://github.com/josephwilk/hystrix-event-stream-clj#how-about-with-jetty

**Comment by MichaelBlume** [comment]
@jiacai2050 I tried that, when I wired it into my project I got an error `No implementation of method: :write-body-to-stream of protocol: #'ring.core.protocols/StreamableResponseBody found for class: lamina.core.channel.Channel` -- I assume some dependency has changed since it worked

**Comment by jiacai2050** [comment]
@MichaelBlume Try this adapter
https://github.com/killme2008/ring-jetty-hystrix-adapter/blob/master/src/ring_jetty_hystrix_adapter/core.clj#L163
