### ISSUE TITLE
Release with updated Ring?

### ISSUE THREAD

**Issue by joephayes** [weavejester/compojure#179]
Now that https://github.com/weavejester/compojure/pull/178 has been merged, would it be possible to get a release? Happy to assist in anyway I can, just let me know.

**Comment by joephayes** [comment]
Hi - following up on this request. I'm happy to open to a PR to bump versions, just let me know.

**Comment by weavejester** [comment]
Done, sorry for the delay.

**Comment by joephayes** [comment]
Thanks!
