### ISSUE TITLE
HEAD requests assume the response is a `clojure.lang.Associative`

### ISSUE THREAD

**Issue by richardcordova** [weavejester/compojure#181]
Most of the routing logic is agnostic as to the form of the response. This has allowed me to pass around a channel as the response, which works well in almost all cases.

HEAD requests are an exception to this as seen in https://github.com/weavejester/compojure/blob/master/src/compojure/core.clj#L33

Could this restriction be relaxed while preserving the existing semantics?

**Comment by weavejester** [comment]
Adding a restriction like that would limit future functionality. Why not wrap the channel in a map and use `compojure.response/Renderable` to add the wrapper automatically?

**Comment by richardcordova** [comment]
Thanks, that seems to work. Good to have it confirmed that it needs to be map.
