### ISSUE TITLE
I have some question in the request used inside the defroutes

### ISSUE THREAD

**Issue by nesteiner** [weavejester/compojure#193]
sorry to bother you again,Mr weavejester
when i use the `defroutes`,i have some question in the request inside
```clojure
(defroutes app-routes
    (GET ... (handler request))
```
after `defroutes`,i def the app by middlewares
```clojure
(def app (-> app-routes
                         middleware1
                         middleware2
                         ...))
```
is this means the request inside app-routes is the **request** which has been proccessed by app??

**Comment by weavejester** [comment]
If I've understood you correctly, yes. The middleware will be applied before app-routes.
