### ISSUE TITLE
Release request, to prevent warnings for Clojure 1.11 users

### ISSUE THREAD

**Issue by stevejmp** [weavejester/compojure#208]
Requesting a new release be pushed.

Due to #205 , warnings are output when running projects, starting REPL's, and reloading deps for Clojure 1.11 users. Since the issue was resolved in #206, pushing a new release would prevent these warnings.

If there's anything I can do to help, please let me know. Thanks!

**Comment by stevejmp** [comment]
Hi, James! Checking in to see if there are any blockers for a new release here. Perhaps anything the community can help with?

**Comment by weavejester** [comment]
Released 1.6.3. Sorry for the delay; it wasn't high on my priority list.
