### ISSUE TITLE
When is a new release coming?

### ISSUE THREAD

**Issue by AriPaaWun** [weavejester/compojure#217]
Do you have any plans for a new release?

I'd like to use a version where [this dependency update](https://github.com/weavejester/compojure/pull/215) is in use.

**Comment by weavejester** [comment]
You can add the updated Ring dependency to your project immediately; you don't need to wait for a release of Compojure.

However, I'll see if I can release a new version this weekend.

**Comment by weavejester** [comment]
Released 1.7.1. Sorry for the wait.
