### ISSUE TITLE
How to check if any routes match?

### ISSUE THREAD

**Issue by sjl** [weavejester/compojure#68]
Is there a way to take a handler defined with `defroutes` and check if a given
URI (or request map) would get routed to something without actually performing
it?

Here's the use case: I want to normalize trailing slashes correctly.  In
a nutshell, I need to write a middleware that does the following:
- If the given request matches a route, just pass it through and do nothing else.
- Otherwise, _if and only if the request + a trailing slash would route somewhere_, return a 301 to that URI.
- Otherwise 404.

It's easy to just always return a redirect when you get a 404 back, but this is
bad because requesting `/bad-url` will return a `301 MOVED PERMANENTLY` to
`/bad-url/` which actually ends up 404'ing.  I want to 404 at the original URL
in that case.

So I need a way to check if a given URI (or request map) would route to
a handler without actually running it through for real.

Just matching `/foo/?` is not a solution, because then `/foo/` and `/foo` are
two distinct URLs that point to the same thing, which is bad.  The non-canonical
one should get 301'ed to the canonical one.

**Comment by Christopher-Bui** [comment]
@weavejester You still think the strategy of automatically redirecting trailing slash urls to non-trailing slash urls is a good idea?

**Comment by weavejester** [comment]
I think this could probably be done in a more optional way with middleware and `wrap-routes`.

So there could be some outer middleware that checks if the URI ends in a slash, and if so it removes the slash, adds a flag to the request, and passes it to the handler. Then we inject some inner middleware with `wrap-routes` that checks for the flag, and if it exists, it sends a redirect response instead.

**Comment by pratyushmittal** [comment]
@weavejester I tried to handle trailing slashes using the `route/not-found` function:

```clojure
(defn page-not-found
    [request]
    (let [uri (:uri request)]
        (if (not (s/ends-with? uri "/"))
            (redirect (str uri "/") 301)
            "Page not found")))

;...
;... In handler
(route/not-found page-not-found)
```

However it seems that we cannot return `redirect` response inside this response. 

I can prepare a pull-request with an if condition to by-pass setting `status 404` if status is already provided. Does it makes sense?

https://github.com/weavejester/compojure/blob/a9e31ed63be1116b5567d6a953e0d52815672d44/src/compojure/route.clj#L54

**Comment by weavejester** [comment]
@pratyushmittal You could just use your `page-not-found` function directly, or better yet, use a route:

```clojure
(GET ":page{/[^/]+}/" [page]
  (redirect page 301))
```

There's no need to change `compojure.route/not-found`.
