### ISSUE TITLE
Add route information to request

### ISSUE THREAD

**Issue by weavejester** [weavejester/compojure#82]
Add route information to the request map for matched routes, e.g.

```clojure
{:route [:get "/"]}
```

Doesn't cost anything to add in, and may be useful for middleware, e.g. authorising by route.

**Comment by tbatchelli** [comment]
+ 1 on this. I am trying to build some ring wrapper to monitor compojure (with datadog) but I need access to the route that matched each request so I can aggregate metrics in a meaningful way.

**Comment by Christopher-Bui** [comment]
Is this still necessary? I'm confused, there's a `:uri` and `:request-method` key in the request already.

**Comment by weavejester** [comment]
`:uri` and `:request-method` don't tell you which route was matched.

**Comment by Christopher-Bui** [comment]
Ok, so if I have this straight:

The uri might be something like "/posts/1" while the matched route would be [:get "/posts/:id"].

Is that correct?

**Comment by weavejester** [comment]
Yes, that's right. The PR in progress is an old one that isn't mergeable, and was written before Clout routes kept their source strings.

**Comment by weavejester** [comment]
Fixed by #140.
