### ISSUE TITLE
URL param conversion

### ISSUE THREAD

**Issue by davejacobs** [weavejester/compojure#87]
Is there a good hook point for transforming URL params before they are made available to the body of a route? That is, it would be awesome if ...

```clojure
(GET "/users/:id" {params :params}
  (users-controller/read params}))
```

... was able to specify a function that could cast `:id` to be an integer by the time it reached the body of the macro.

I've looked in `compojure.core` and don't see anything immediately obvious. Any recommendations on how to solve this?

Thanks!
David

**Comment by weavejester** [comment]
Superseded by #131
